apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: business-service
data:
  SERVER_PORT: "8082"
  SPRING_APPLICATION_NAME: "analytics-service"
  COMMON_DATASOURCE_PRIMARY_URL: "jdbc:postgresql://postgres:5432/bioinformatics_db"
  COMMON_DATASOURCE_REPLICA_URL: "jdbc:postgresql://postgres-replica:5432/bioinformatics_db"
  COMMON_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  COMMON_KAFKA_CONSUMER_ACK_MODE: "manual"

