apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: coordination
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: client

