apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: messaging-ui
data:
  KAFKA_CLUSTERS_0_NAME: "local-cluster"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
  KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
  SERVER_PORT: "8080"
  JAVA_OPTS: "-Xms128m -Xmx384m"

