<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bioinformatics</groupId>
        <artifactId>bioinformatics</artifactId>
        <version>${revision}</version>
        <relativePath>../../../backend/pom.xml</relativePath>
    </parent>


    <artifactId>shared-models</artifactId>
    <name>Archetype - shared-models</name>
    <description>Shared common library for Bioinformatics microservices</description>

    <dependencies>
        <!-- ── Lombok ──────────────────────────────────────────────── -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
