apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: import-uploads
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: import-service
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: business-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # UniProt uploads can reach 2 GB each

