package com.bioinformatics.dashboard.audit.service;

import com.bioinformatics.dashboard.audit.dto.AuditAction;
import com.bioinformatics.dashboard.audit.dto.AuditLogDto;
import com.bioinformatics.dashboard.audit.dto.AuditStatus;
import com.bioinformatics.dashboard.audit.dto.AuditWebDetails;
import com.bioinformatics.dashboard.audit.entity.AuditLog;
import com.bioinformatics.dashboard.audit.mapper.AuditLogMapper;
import com.bioinformatics.dashboard.audit.repository.AuditLogRepository;
import com.bioinformatics.shared.models.security.UserPrincipal;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

/**
 * Service that persists audit records generated by dashboard operations.
 *
 * <p>Audit entries are written asynchronously so that request handling remains fast while the system retains a
 * chronological trail of user actions, security outcomes, and API access patterns.</p>
 */
@Service
@RequiredArgsConstructor
@Transactional
@Slf4j
public class AuditService {
    private final AuditLogRepository auditLogRepository;
    private final AuditLogMapper mapper;

    /**
     * Persists an audit log entry asynchronously.
     *
     * @param actor the authenticated user performing the action, or null for anonymous/system context
     * @param attemptedUsername the username attempted or acting username when actor is null
     * @param action the audited action enum
     * @param targetId identifier of the target resource, or null
     * @param status outcome of the audited operation
     * @param webDetails optional request metadata collected from the current request
     */
    @Async("auditExecutor")
    public void save(UserPrincipal actor, String attemptedUsername, AuditAction action, String targetId, AuditStatus status, AuditWebDetails webDetails) {
        log.debug("[DASHBOARD][AUDIT] Persisting audit record actor={} action={} targetId={} status={}",
                actor != null ? actor.id() : attemptedUsername, action, targetId, status);
        var auditLog = new AuditLog();
        auditLog.setAction(action);
        auditLog.setTarget(action.getDefaultTarget());
        auditLog.setTargetId(targetId);
        auditLog.setStatus(status);
        if (actor != null) {
            auditLog.setActorUsername(actor.id());
        } else {
            auditLog.setActorUsername(attemptedUsername != null ? attemptedUsername : "UNKNOWN");
        }
        if (webDetails != null) {
            auditLog.setHttpMethod(webDetails.httpMethod());
            auditLog.setEndpoint(webDetails.endpoint());
            auditLog.setIpAddress(webDetails.ipAddress());
        } else {
            auditLog.setHttpMethod("SYSTEM");
            auditLog.setEndpoint("INTERNAL");
        }
        auditLogRepository.save(auditLog);
        log.debug("[DASHBOARD][AUDIT] Audit record saved action={} status={} targetId={}", action, status, targetId);
    }

    /**
     * Retrieves the paginated audit log entries for a user.
     *
     * @param username the actor username to filter by
     * @param pageable pagination settings
     * @return page of audit DTOs for the selected user
     */
    public Page<AuditLogDto> findByUser(String username, Pageable pageable) {
        log.debug("[DASHBOARD][AUDIT] Looking up audit history for user={}", username);
        return auditLogRepository.findByActorUsername(username, pageable).map(mapper::toDto);
    }
}
