apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-db-data
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: gitea-db
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: config-repository-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

