apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-server-config
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: service-discovery
data:
  SERVER_PORT: "8761"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
  EUREKA_CLIENT_FETCH_REGISTRY: "false"
  EUREKA_INSTANCE_HOSTNAME: "discovery-server"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  LOG_PATH: "/app/logs"

