apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: service-discovery
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: discovery-server
  ports:
    - name: http
      port: 8761
      targetPort: http
      nodePort: 30761

