apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: gateway
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: "api-gateway"
  SPRING_DATA_REDIS_CONNECT_TIMEOUT: "2000"

