apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

