apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-data
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: postgres-replica
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

