apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: postgres-replica
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres-replica
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres

