apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: business-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: 8081
      targetPort: http

