apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin-config
  namespace: bio-dashboard
  labels:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/part-of: bio-dashboard
    app.kubernetes.io/component: tracing
data:
  STORAGE_TYPE: "mem"
  JAVA_OPTS: "-Xms128m -Xmx384m"

